language: node_js
node_js:
    - "lts/*"
cache:

    directories:
        - ~/.npm
        - ./node_modules
        - ~/.cache
    override:
        - npm ci
        - npm run cy:verify
branches:
    only:
        - develop
before_script:
    - npm install -g @angular/cli
script:
    - npm install
    - ng build --prod
    - npm run jest:run
    - npm run cy:verify
    - npm run ci:cy-run
deploy:
    skip_cleanup: true
    provider: firebase
    token:
        secure: $FIREBASE_TOKEN
