
language: node_js

node_js:
    - "lts/*"

cache:

    directories:
        - ~/.npm
        - ./node_modules
        - ~/.cache
    override:
        - npm ci
        - npm run cy:verify

install:
    - npm ci

script:
    - ng build --prod
    - npm run cy:verify
    - npm run ci:cy-run
    - ng build --prod --base-href /toh-cypress/
    - mv dist/toh-cypress/index.html dist/toh-cypress/404.html

deploy:
  provider: firebase
  skip_cleanup: true
  keep_history: true
  token:
    secure: $FIREBASE_TOKEN
   project: "appointments-ui"
  on:
    branch: develop

